# Generated by Django 2.2 on 2019-04-23 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_id', models.BigIntegerField(verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('company', models.CharField(max_length=50, verbose_name='所属公司')),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进入时间')),
                ('leave_time', models.DateTimeField(auto_now=True, verbose_name='离开时间')),
                ('reason', models.CharField(max_length=100, verbose_name='事由')),
                ('finish', models.BooleanField(default=False, verbose_name='是否结束')),
                ('accompany_ops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitorecord.Ops')),
                ('visitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitorecord.Visitors')),
            ],
        ),
    ]
