# Generated by Django 2.2 on 2019-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='电话'),
        ),
    ]
