# Generated by Django 2.2.7 on 2019-12-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnspod',
            name='operation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
