# Generated by Django 2.2.7 on 2019-12-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namesystem', '0002_auto_20191216_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnspod',
            name='Recordvalue',
            field=models.CharField(max_length=200),
        ),
    ]
