# Generated by Django 2.2.7 on 2019-12-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namesystem', '0003_auto_20191216_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnspod',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
